name = "mise-versions"
main = "dist/worker.js"
compatibility_date = "2024-01-06"
workers_dev = true

[[queues.producers]]
queue = "mise-versions"
binding = "MISE_VERSIONS_QUEUE"

[[queues.consumers]]
queue = "mise-versions"
max_batch_size = 100
max_batch_timeout = 60
